config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "dashboard" => "dashboard#index", as: :dashboard
  root "home#index"

  resources :profile, only: [ :index ]

  resources :categories do
    resources :tasks
  end
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="bg-gradient-to-t from-orange-400 to-amber-200 font-[Sora] flex flex-col items-center justify-center text-[1.5rem] static min-h-screen mt-auto w-full box-border">
  <div class="absolute top-0 right-0 flex gap-2 ">
    <div>
      <%= link_to "Profile", profile_index_path, class: "hover:text-[#5486e6] hover:underline hover:cursor-pointer font-bold" %>
    </div>
    <div>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "hover:text-[#5486e6] hover:underline hover:cursor-pointer font-bold"  %>
    </div>
  </div>
    <div class="absolute top-0 left-0 self-start justify-self-start" style="margin-left: 15px; margin-top: 15px">
    <div class="">
      <%= render partial: 'categories/new' %>
    </div>
  </div>
  <div class="flex flex-col items-center justify-center">
    <div class="text-[#000000] text-[2rem] font-bold">
      Hello <%= current_user.username %>
    </div>
  </div>
  <div class="flex flex-col items-center justify-center">
    <% if current_user.categories.count != 0 %>
      <h2 class="text-center">Your task due:</h2>
        <div class="flex flex-col items-center justify-between bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem] gap-1 min-h-[200px] rounded-[5px] border-[2px] border-black text-[1.5rem] p-2">
          <% if current_user.tasks.count != 0 || nil %>
            <h3 class="text-center font-semibold font-[Sora]">
              <%= current_user.tasks.first.task_title %>
            </h3> 
            <div class="flex items-start justify-center font-[Manrope]">
              <%= current_user.tasks.first.task_body %>
            </div>
            <div class="flex">
              <div class="text-[1rem] flex items-center justify-center text-[#9e9e9e] hover:text-black">
                <%= current_user.tasks.first.created_at.localtime.to_formatted_s(:short) %>
              </div>
              <div class="text-[1rem]  flex items-center justify-center">
                <%= link_to "📝", edit_category_task_path(current_user.tasks.first.category_id, current_user.tasks.first.id), locals: { task_id: current_user.tasks.first.id } %>
              </div>
              <div>
                <%= button_to "x", category_task_path(current_user.tasks.first.category_id, current_user.tasks.first.id), data:{ turbo_method: :delete, turbo_confirm: 'Are you sure?' }, method: :delete, class: "hover:underline hover:cursor-pointer font-bold" %>
              </div>
              <% else %>
              <div> Create a task! </div>
              <% end %>
        </div>

        </div>
      <div className="test" class="flex flex-wrap justify-center items-center bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem] pt-3 border-1 p-5 mt-5">
        <%= render partial: 'categories/category', collection: current_user.categories %>
        <% else %>
          <h2>Begin and create a category for your tasks!</h2>
        <% end %>
      </div>
  </div>

</div>