config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "dashboard" => "dashboard#index", as: :dashboard
  root "home#index"

  resources :profile, only: [ :index ]

  resources :categories do
    resources :tasks
  end
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :task_title, presence: true
  validates :task_body, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  # def index
  # end

  # def show
  # end

  # def new
  # end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    @task.category_id = params[:category_id]

    if @task.save
      redirect_to dashboard_path
    else
    p @task.errors.messages
    p "@task.user_id: #{@task.user_id}"
    p "@task.category_id: #{@task.category_id}"
    end
  end

  def edit
    @task = Task.find(params[:id])
    render :edit
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
    redirect_to dashboard_path
    else
      p @task.errors.messages
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to dashboard_path
    else
      p @task.errors.messages
    end
  end

  private
  def task_params
    params.require(:task).permit(:task_title, :task_body)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_new.html.erb
<%= form_with scope: :task, url: category_tasks_path(category_id), method: :post, local: true do |f| %>

<%= render 'tasks/shared/form', f: f %>

<% end %>

app/views/tasks/_task.html.erb
<div class=" flex flex-col bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem] p-3 border-[2px] border-black border-t-0 rounded-[5px] wrap-break-word  break-all min-h-0 w-full h-full">
  <div class="flex flex-col min-w-0 min-h-0 gap-2">
    <h3 class="text-center font-semibold font-[Sora]"><%= task.task_title %></h3> 
        <div class="wrap-anywhere whitespace-break-spaces break-all flex items-start justify-center font-[Manrope]"><%= task.task_body %></div>
      <div class="flex items-center justify-end h-full p-1 pt-2 text-[#9e9e9e] hover:text-black">
        <div class="flex items-center justify-between">
          <div class="flex items-center justify-between">
            <div class="text-[1rem]">
              <%= task.created_at.localtime.to_formatted_s(:short) %>
            </div>
          </div>
          <div class="flex items-center justify-between text-[0.8rem]">
            <div>
              <%= link_to "📝", edit_category_task_path(category_id, task.id), locals: { task_id: task.id } %>
            </div>
            <div>
              <%= button_to "x", category_task_path(category_id, task.id), data:{ turbo_method: :delete, turbo_confirm: 'Are you sure?' }, method: :delete, class: "hover:text-[#5486e6] hover:underline hover:cursor-pointer text-[1rem] font-semibold" %> 
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="flex flex-col text-[2rem] items-center justify-center font-[Manrope] bg-gradient-to-bl from-orange-400 to-amber-200 w-full min-h-screen">
  <%= form_with scope: :task, url: category_task_path, method: :patch, local: true do |f| %>

  <%= render 'tasks/shared/form', f: f %>

  <% end %>
</div>