config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "dashboard" => "dashboard#index", as: :dashboard
  root "home#index"

  resources :profile, only: [ :index ]

  resources :categories do
    resources :tasks
  end
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
  validates :user_id, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  # def index
  #   @categories = Category.all
  # end

  # def show
  # end

  # def new
  # end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    if @category.save
      redirect_to dashboard_path
    else
      p "Huh"
    end
  end

  def edit
    @category = Category.find(params[:id])
    render :edit
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)

    redirect_to dashboard_path
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to dashboard_path
    else
      p @category.errors.messages
    end
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class=" flex flex-col items-center justify-center not-first-of-type:m-1 bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem] rounded-[5px] min-h-0 h-full">
  <div class="flex flex-col min-h-0 max-w-[410px] rounded-[6px] mb-4">
    <div class="flex items-center justify-between bg-[#f8d300] gap-1 border-[2px] border-black rounded-[5px] min-w-[410px]" className="categories-wrapper">
      <h3 class="p-3 font-[Sora]"><%= category.title %></h3> 
      <div class="flex justify-between">
        <div class="p-3"><%= link_to "Edit", edit_category_path(category.id), class: "text-[1.2rem]" %></div>
        <div class="p-3"><%= button_to "x", category_path(category.id), data:{ turbo_method: :delete,   turbo_confirm: 'Are you sure?' }, method: :delete, class: "hover:underline hover:cursor-pointer font-bold" %></div>
      </div>
    </div>
    <div class="tasks-wrapper min-h-0 rounded-[6px]">
    <%= render partial: 'tasks/task', collection: category.tasks, locals: { category_id: category.id } %>
    <%= render partial: 'tasks/new', locals: { category_id: category.id } %>
    </div>
  </div>
</div>

app/views/categories/_new.html.erb
<%= form_with scope: :category, url: categories_path, local: true do |f| %>

<%= render 'categories/shared/form', f: f %>

<% end %>

app/views/categories/edit.html.erb
<div class="flex flex-col text-[2rem] items-center justify-center font-[Manrope] bg-gradient-to-bl from-orange-400 to-amber-200 w-full min-h-screen">
  <%= form_with scope: :category, url: category_path, method: :patch, local: true do |f| %>

  <%= render 'categories/shared/form', f: f %>

  <% end %>
</div>

app/views/categories/index.html.erb
something